name: Create Azure ARM Environment
author: Isaac Shabtay
description: Creates an Azure ARM environment
branding:
  icon: cloud
  color: white
inputs:
  environment-name:
    description: Name of Cloudify environment to create
    required: true
  labels:
    description: |
      A labels list of the form <key>:<value>,<key>:<value>.
      Any comma and colon in <value> must be escaped with \.
      The labels’ keys are saved in lowercase.
    required: false
    default: "-"
  resource-group:
    description: Name of resource group to create
    required: true
  template-file:
    description: URL/path to template file
    required: true
  parameters-file:
    description: YAML/JSON file containing template parameters
    required: false
    default: "-"
  location:
    description: Azure location to create resource group in
    required: false
    default: "-"
  outputs-file:
    description: |
      Path to JSON file to receive the Cloudify environment's outputs
      and capabilities
    required: false
    default: "-"
outputs:
  environment-data:
    description: The Cloudify environment's outputs and capabilties
runs:
  using: docker
  image: docker://cloudifyplatform/cloudify-cli:6.3.0
  entrypoint: cfyci
  args:
    - arm
    - '--name'
    - ${{ inputs.environment-name }}
    - '--labels'
    - ${{ inputs.labels }}
    - '--resource-group'
    - ${{ inputs.resource-group }}
    - '--template-file'
    - ${{ inputs.template-file }}
    - '--parameters-file'
    - ${{ inputs.parameters-file }}
    - '--location'
    - ${{ inputs.location }}
    - '--outputs-file'
    - ${{ inputs.outputs-file }}
